apiVersion: apps/v1
kind: Deployment
metadata:
        name: phpmyadmin-deployment
        labels:
                app: phpmyadmin
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: phpmyadmin
        template:
                metadata:
                        labels:
                                app: phpmyadmin
                spec:
                        containers:
                                - name: phpmyadmin
                                  image: phpmyadmin
                                  ports:
                                          - containerPort: 8080
                                  env:
                                          - name: PMA_USER
                                            valueFrom:
                                                    secretKeyRef:
                                                            name: mariadb-secret
                                                            key: mariadb-username
                                          - name: PMA_PASSWORD
                                            valueFrom:
                                                    secretKeyRef:
                                                            name: mariadb-secret
                                                            key: mariadb-password
                                          - name: PMA_HOST
                                            valueFrom:
                                                    configMapKeyRef:
                                                            name: mariadb-configmap 
                                                            key: database_url
---
apiVersion: v1
kind: Service
metadata:
        name: phpmyadmin-service
spec:
        selector:
                app: phpmyadmin
        type: LoadBalancer
        ports:
                - protocol: TCP
                  port: 8080
                  targetPort: 8080
                  nodePort: 31000







